In [24]:
import numpy as np

In [74]:
#1
array_1 = np.array([0,0,0,0,0,0,0,0,0,0])

In [75]:
#2
array_2 = np.array([1,1,1,1,1])

In [76]:
#3
array_3 =np.array([1,2,3,4,5,6,7,8,9,10])

In [98]:
#4
array_3[5] = 100
print(array_3)

[  1   2   3   4   5 100   7   8   9  10]


In [79]:
#5
reserved_array = array_3[::-1]

print(reserved_array)

In [99]:
#6
multi_array = np.array([[1,2,3],[1,2,3],[1,2,3]])

print(multi_array)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [100]:
#7
a = np.array([[1,2,3]])
b = np.array([[4,5,6]])

print(a+b)

[[5 7 9]]
